# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MLtest' do
  use_frameworks!

    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Alamofire-SwiftyJSON'

end
